Minor misspelling fix (RunMode::PeformLayout -> RunMode::PerformLayout)
DioxusLabs/taffy pull request #485
Opened 2023-05-26 15:01 UTC by inobelar

# Objective

> Why did you make this PR?

I found minor misspelling. `RunMode::PeformLayout` changed into `RunMode::PerformLayout` (added missing `r`)

2023-05-26 15:06 UTC, alice-i-cecile approved these changes

2023-05-26 15:07 UTC, alice-i-cecile commented
Sadly breaking, but we should roll this up into the next major version release. Thanks!

2023-05-27 12:48 UTC, Weibye approved these changes

2023-05-30 22:36 UTC, nicoburns requested changes
Well noticed! This needs a changelog entry (`RELEASES.md`). Otherwise looks good to me :)

2023-05-31 10:22 UTC, nicoburns approved these changes

2023-05-31 10:44 UTC, merged