floor alignment offset
DioxusLabs/taffy pull request #549
Opened 2023-10-04 11:40 UTC by robtfm

# Objective

correct space-xxx behaviour for cramped containers.

## Context

i noticed a difference in layout between chrome and firefox vs taffy (via bevy) when the computed alignment for non-first items returns a negative value. it seems to be corrected by flooring the offset at zero.

i don't know for sure if the floor should be with the `gap` or without, i assumed with. 

screenshots below for containers with `justify-content` set to each space-xxx mode
note the "modified" screenshots still show differences in the last two columns where the height is a negative number of px - i am not sure if there's a good spec for that, but i can work around it by just supplying `Auto` if the input is negative.

space-between original
![space-between original](https://github.com/DioxusLabs/taffy/assets/50659922/f970778a-b4d4-4f6e-9952-ee703b05c7c7)
modified
![space-between modified](https://github.com/DioxusLabs/taffy/assets/50659922/2671ce5f-17fb-4f49-add1-455b5fa20a7e)

space-evenly original
![space=-evenly original](https://github.com/DioxusLabs/taffy/assets/50659922/1b2a8987-c1ce-49cd-b0c6-d701ee48385a)
modified
![space-evenly modified](https://github.com/DioxusLabs/taffy/assets/50659922/d1f82d08-ba62-4945-a805-1fe6e274791c)

space-around original
![space-around original](https://github.com/DioxusLabs/taffy/assets/50659922/ba75fb19-63fc-4d64-a576-a3fe0b011609)
modified
![space-around modified](https://github.com/DioxusLabs/taffy/assets/50659922/a0910c2f-97ee-4428-be89-359314a914d6)

2023-10-04 12:54 UTC, nicoburns requested changes
Hi, and thanks for the PR!

Good catch - that value definitely shouldn't ever be negative! My intuition is that it is `free_space` that ought to be floored at zero, as the concept of "free space" is such that it should always be non-negative. I suspect `gap` may also need to be floored at zero. But that should happen elsewhere (when the layout algorithm first accesses the `gap` style) as gap is set by the user and a negative value is never valid. I think it is fine for this code to assume that `gap` is positive.

Having said that, we usually try not to rely on intuition but on generated tests that assert that our output is identical to Chrome (unless we determine that Chrome's output is incorrect). As such I would like to request the following changes:

- Change the code to floor `free_space`, either at the top of this function, or in the callers (this function is used by both the flexbox and grid algorithms). I'd be tempted to put the floor where the `free_space` is first being computed.
- Add a line to the changelog (`RELEASES.md`) under "Fixes"
- Would it be possible for you to turn the HTML you have been testing Chrome/Firefox's output with into Taffy "generated tests". This would involve:
     - Adding HTML file(s) to `test_fixtures/flex` (duplicate one of the existing ones as a template, and modify the "test root" with your HTML).
     - Running `cargo gentest` (you will need Chrome and `chromedriver` installed) to generate the tests
     - You can then actually run the new tests with `cargo test`
     
     Failing that, could you post a sample of the HTML that triggers this issue as a comment on this issue so that we can we create the tests ourselves?

2023-10-04 14:14 UTC, nicoburns commented
> the code i used is below (can provide the bevy code too but i guess you don't need that?), just changing the justify-content for each case. i'm not really keen to add the tests, i think it will take me much longer than someone with more familiarity ...

Yeah, no worries. I'll take a look later. The HTML you provided is really helpful.

> also just to point out - i made this patch to the 0.3.x branch, not sure if that's what you want.

We normally try to land fixes on `main` first and then backport to release branches. So against would be preferable. For such a small fix it's easy for us to rebase though.

> i think this would be incorrect - chrome only floors non-first items (see the way the lines go above the boxes in the evenly and around screenshots in cols 6-7.

Ah ok. That's good to know. I'll play around with the tests and try to pin down the behaviour.

2023-10-04 14:28 UTC, nicoburns commented
We probably ought to implement the "safe" alignment variants too. With `justify-content: safe space-evenly` you get this (Chrome):

<img width="1293" alt="Screenshot 2023-10-04 at 15 26 43" src="https://github.com/DioxusLabs/taffy/assets/1007307/5106b6a9-cf78-4a7d-a0f5-cd7e799e9059">

2023-10-05 10:44 UTC, closed without merging

2023-10-05 11:20 UTC, nicoburns commented
@robtfm Taffy `v0.3.15` has been released with a fix for this issue :)

2023-10-05 11:20 UTC, robtfm commented
awesome, thank you :)