Make `serde` dependency compatible with `no_std` environments
DioxusLabs/taffy pull request #592
Opened 2023-12-10 17:25 UTC by konall

Feature `serde` of `taffy` was rigidly set to depend on the `serde` crate with its default features (ie: `std`) enabled- this meant that despite disabling the `std` feature in `taffy` it still would not compile for `no_std` targets when the `serde` feature was enabled.

This was a straightforward fix, simply opting out of `serde` default features and selectively re-enabling them alongside the corresponding `taffy` features.

See here for a quick reference affirming Serde `no_std` compatibility: https://serde.rs/no-std.html

2023-12-10 17:47 UTC, nicoburns commented
This seems sensible. I should want you that while Taffy works great without std, it’s pretty limited without alloc. I’d be interested to know what your use case is, and whether you have access to dynamic allocation.

2023-12-10 18:24 UTC, konall commented
I'm experimenting with an embeddable GUI engine, for which I'm using Taffy with just the `alloc` feature- I agree that it would be quite tricky to navigate without `alloc`, but I just lined the alloc-less Taffy feature up with the alloc-less Serde feature for completeness

2023-12-11 03:27 UTC, alice-i-cecile approved these changes

2023-12-11 03:28 UTC, alice-i-cecile requested changes
LGTM once there's a brief note in https://github.com/DioxusLabs/taffy/blob/main/RELEASES.md

2023-12-11 12:23 UTC, nicoburns approved these changes
@konall This is failing CI due to unrelated clippy lint failures (due to new lints in a newer version of clippy). I've fixed these on `main`, so if you rebase this on top of latest `main` then we can merge :)

2023-12-11 16:38 UTC, alice-i-cecile approved these changes

2023-12-11 16:38 UTC, merged