add get_disjoint_node_context_mut to tree
DioxusLabs/taffy pull request #596
Opened 2023-12-30 18:21 UTC by dylanblokhuis

Useful method when dealing with mutable borrows between a parent and child node at the same time.

2023-12-30 22:28 UTC, alice-i-cecile approved these changes

2023-12-30 22:29 UTC, alice-i-cecile requested changes
Actually, please add an entry to RELEASES.md :) Looks useful and correct otherwise though.

2023-12-31 11:08 UTC, dylanblokhuis commented
@alice-i-cecile I added an entry to RELEASES.md.

2024-01-01 02:47 UTC, nicoburns approved these changes

2024-01-01 03:14 UTC, merged