Add Size::new_with_cross utility method
DioxusLabs/taffy pull request #609
Opened 2024-02-07 13:43 UTC by Taym95

# Objective
Fixes #547

2024-02-07 13:44 UTC, Taym95 commented on src/geometry.rs
> +    pub fn new_with_cross(direction: FlexDirection, value: Option<f32>) -> Self {
can not be named `cross` since name is used in `Size<T>`

2024-02-08 21:21 UTC, nicoburns requested changes
PR generally looks good to me, but the name `new_with_cross` seems quite verbose.

I believe the method could be named just `cross` as static methods (no `self` parameter) do not conflict with object methods (with a `self` parameter). But perhaps the most idiomatic name would be `from_cross`. Could you change the name of the method to either `cross` or `from_cross`?

2024-02-08 21:33 UTC, alice-i-cecile commented
I prefer `from_cross`

2024-02-08 22:03 UTC, nicoburns commented
Checking the CI results, this method also needs to be feature flagged so that it only exists when the `flexbox` feature is enabled.

2024-02-12 08:07 UTC, nicoburns approved these changes

2024-02-12 08:07 UTC, merged