fix: single-line flex-container should clamp the line's cross-size
DioxusLabs/taffy pull request #638
Opened 2024-04-08 07:08 UTC by TtTRz

# Objective

In Taffy, missing a step when calculate the cross size of each flex line.

``` 
//  If the flex container is single-line, then clamp the line’s cross-size to be within the container’s computed min and max cross sizes.
```

2024-04-08 21:42 UTC, nicoburns requested changes
I've requested a couple of changes, but this generally looks very good: thanks for the PR!

We may also wish to generally review the interaction of:
- The logic added in this PR
- The "if" statement at the top of `calculate_cross_size`
- The presence of min/max sizes (with no preferred size)
- The presence of wrap vs. nowrap
But that does not need to happen in this PR.

2024-04-09 04:29 UTC, TtTRz commented on src/compute/flexbox.rs
> +        if flex_lines.len() == 1 {
I noticed that `flex_lines.len() == 1` is used in [https://github.com/DioxusLabs/taffy/blob/main/src/compute/flexbox.rs#L1352](https://github.com/DioxusLabs/taffy/blob/main/src/compute/flexbox.rs#L1352) to determine if it is a single line. 
I've also looked at some other browser layout engine implementations, I see no difference between "nowrap" and "happends to be single-line", but i'll add some tests to check it.

2024-04-09 04:34 UTC, nicoburns commented on src/compute/flexbox.rs
> +        if flex_lines.len() == 1 {
> I've also looked at some other browser layout engine implementations, I see no difference between "nowrap" and "happends to be single-line", but i'll add some tests to check it.

If you add `flex-wrap: wrap` (the default is `nowrap`) to the test you created for this PR then you'll find that the layout ends up changing. I rather suspect that line 1532 is wrong too (although that `if` does also include the flex_wrap property later in the condition).

2024-04-09 07:21 UTC, TtTRz commented on src/compute/flexbox.rs
> +        if flex_lines.len() == 1 {
I found the difference just like you said, i think we should use flex_wrap to determine if it is single-line or not.

I add some test cases and it looks fine :)
* padding/border
* min/max size
* wrap/no-wrap

2024-04-09 07:25 UTC, TtTRz commented on src/compute/flexbox.rs
> +                cross_max_size.maybe_sub(cross_axis_padding_border),
I added test cases

2024-04-09 07:36 UTC, nicoburns approved these changes
This looks good to me now. Thanks for the fixes (and the tests)!

2024-04-09 07:36 UTC, merged

2024-04-09 07:39 UTC, TtTRz commented
> This looks good to me now. Thanks for the fixes (and the tests)!

Thanks for the review XD!