fix description in traits.rs
DioxusLabs/taffy pull request #731
Opened 2024-10-23 10:12 UTC by tistatos

# Objective

Missed to update the documentation in `traits.rs` in #730 

## Feedback wanted

For my own understanding and for others clarification, I also added the reason why this example is limited to `TraversePartialTree` - Hopefully it's correctly described!

2024-10-31 06:50 UTC, nicoburns requested changes
This is not wrong, but I don't think it will make sense to people reading that part of the docs (who may well not know what `TraversePartialTree` is). Perhaps this would make more sense as a doc comment in the example itself?

2024-10-31 07:41 UTC, tistatos commented
That is a valid point! I will add it to the example. Would you like me to add it at the head of the file? Or in connection with the `impl TraversePartialTree` ?

2024-10-31 07:43 UTC, nicoburns commented
I think at the head of the file would make most sense.

2024-11-04 23:50 UTC, nicoburns approved these changes

2024-11-04 23:50 UTC, merged